In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import os

In [7]:
os.getcwd()

location = os.path.join(os.getcwd(), 'data')

In [92]:
dfs = [pd.read_csv(os.path.join(location, filename)) for filename in os.listdir(location)]

In [24]:
df = pd.concat(dfs, ignore_index=True)

In [27]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
esi,558023.0,3.012387,0.869109,1.0,2.0,3.0,4.0,5.0
age,560469.0,49.876767,20.417138,18.0,32.0,49.0,64.0,108.0
cc_abdominalcramping,557895.0,0.001047,0.032337,0.0,0.0,0.0,0.0,1.0
cc_abdominaldistention,557895.0,0.001126,0.033585,0.0,0.0,0.0,0.0,2.0
cc_abdominalpain,557895.0,0.097411,0.296607,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...
cc_woundcheck,557895.0,0.004219,0.064820,0.0,0.0,0.0,0.0,1.0
cc_woundinfection,557895.0,0.002863,0.053426,0.0,0.0,0.0,0.0,1.0
cc_woundre-evaluation,557895.0,0.001233,0.035095,0.0,0.0,0.0,0.0,1.0
cc_wristinjury,557895.0,0.001393,0.037293,0.0,0.0,0.0,0.0,1.0
cc_wristpain,557895.0,0.002518,0.050156,0.0,0.0,0.0,0.0,2.0

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560480 entries, 0 to 560479
Columns: 217 entries, dep_name to cc_wristpain
dtypes: float64(202), object(15)
memory usage: 927.9+ MB

In [34]:
df.columns

Index(['dep_name', 'esi', 'age', 'gender', 'ethnicity', 'race', 'lang',
       'religion', 'maritalstatus', 'employstatus',
       ...
       'cc_vaginaldischarge', 'cc_vaginalpain', 'cc_weakness', 'cc_wheezing',
       'cc_withdrawal-alcohol', 'cc_woundcheck', 'cc_woundinfection',
       'cc_woundre-evaluation', 'cc_wristinjury', 'cc_wristpain'],
      dtype='object', length=217)

In [36]:
df.dtypes.value_counts()

float64    202
object      15
Name: count, dtype: int64

In [38]:
df.select_dtypes(include=['object']).columns

Index(['dep_name', 'gender', 'ethnicity', 'race', 'lang', 'religion',
       'maritalstatus', 'employstatus', 'insurance_status', 'disposition',
       'arrivalmode', 'arrivalmonth', 'arrivalday', 'arrivalhour_bin',
       'previousdispo'],
      dtype='object')

In [52]:
cols = df.select_dtypes(include=['object'])
cols.head(10)

,dep_name,gender,ethnicity,race,lang,religion,maritalstatus,employstatus,insurance_status,disposition,arrivalmode,arrivalmonth,arrivalday,arrivalhour_bin,previousdispo
0,B,Male,Non-Hispanic,White or Caucasian,English,NaN,Married,Full Time,Commercial,Admit,Walk-in,June,Thursday,11-14,No previous dispo
1,A,Male,Non-Hispanic,White or Caucasian,English,NaN,Married,Full Time,Commercial,Discharge,ambulance,May,Sunday,07-10,Admit
2,B,Female,Non-Hispanic,White or Caucasian,English,Catholic,Married,Part Time,Commercial,Admit,ambulance,September,Friday,11-14,Discharge
3,C,Female,Non-Hispanic,White or Caucasian,English,Catholic,Married,Part Time,Commercial,Discharge,Car,March,Saturday,11-14,Admit
4,C,Male,Non-Hispanic,White or Caucasian,English,Jewish,Married,Full Time,Commercial,Admit,Car,April,Sunday,23-02,No previous dispo
5,B,Female,Non-Hispanic,White or Caucasian,English,NaN,Single,Disabled,Medicare,Discharge,Walk-in,July,Friday,15-18,No previous dispo
6,A,Male,Non-Hispanic,Black or African American,English,NaN,Single,Full Time,Medicaid,Discharge,Walk-in,June,Monday,15-18,No previous dispo
7,B,Male,Non-Hispanic,Black or African American,English,NaN,Single,Full Time,Other,Discharge,Walk-in,May,Monday,15-18,Discharge
8,A,Male,Non-Hispanic,Black or African American,English,NaN,Single,Part Time,Other,Discharge,ambulance,March,Tuesday,15-18,No previous dispo
9,A,Male,Non-Hispanic,Black or African American,English,NaN,Single,Part Time,Other,Discharge,Car,July,Wednesday,15-18,Discharge

In [57]:
cols.isna().sum() / len(cols)

dep_name            0.000000
gender              0.000000
ethnicity           0.000000
race                0.000046
lang                0.000000
religion            0.241218
maritalstatus       0.000000
employstatus        0.000000
insurance_status    0.000000
disposition         0.000000
arrivalmode         0.039045
arrivalmonth        0.000000
arrivalday          0.000000
arrivalhour_bin     0.000000
previousdispo       0.000000
dtype: float64

In [65]:
df.columns.array.to_numpy().tofile('columns.txt', sep='\n')

In [90]:
cc_mask = df.columns.str.contains('cc')
base_df = df.loc[:, ~cc_mask]


cc_df = df.loc[:, cc_mask]
cc_df.dtypes.value_counts()

selected_cc = cc_df.describe().T["mean"].sort_values(ascending=False)[:10].index.to_list()

columns_mask = selected_cc + base_df.columns.to_list()
columns_mask

['cc_abdominalpain',
 'cc_other',
 'cc_chestpain',
 'cc_shortnessofbreath',
 'cc_backpain',
 'cc_fall',
 'cc_alcoholintoxication',
 'cc_motorvehiclecrash',
 'cc_dizziness',
 'cc_cough',
 'dep_name',
 'esi',
 'age',
 'gender',
 'ethnicity',
 'race',
 'lang',
 'religion',
 'maritalstatus',
 'employstatus',
 'insurance_status',
 'disposition',
 'arrivalmode',
 'arrivalmonth',
 'arrivalday',
 'arrivalhour_bin',
 'previousdispo']

In [94]:
df.loc[:, columns_mask]

,cc_abdominalpain,cc_other,cc_chestpain,cc_shortnessofbreath,cc_backpain,cc_fall,cc_alcoholintoxication,cc_motorvehiclecrash,cc_dizziness,cc_cough,...,religion,maritalstatus,employstatus,insurance_status,disposition,arrivalmode,arrivalmonth,arrivalday,arrivalhour_bin,previousdispo
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,Married,Full Time,Commercial,Admit,Walk-in,June,Thursday,11-14,No previous dispo
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,Married,Full Time,Commercial,Discharge,ambulance,May,Sunday,07-10,Admit
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Catholic,Married,Part Time,Commercial,Admit,ambulance,September,Friday,11-14,Discharge
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Catholic,Married,Part Time,Commercial,Discharge,Car,March,Saturday,11-14,Admit
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Jewish,Married,Full Time,Commercial,Admit,Car,April,Sunday,23-02,No previous dispo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560475,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,Single,Full Time,Other,Discharge,Car,June,Monday,15-18,No previous dispo
560476,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Episcopal,Married,Full Time,Commercial,Admit,Car,March,Friday,11-14,No previous dispo
560477,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Catholic,Widowed,Retired,Medicare,Admit,ambulance,May,Saturday,15-18,No previous dispo
560478,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Catholic,Widowed,Retired,Medicare,Admit,ambulance,May,Sunday,07-10,Admit
560479,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,Catholic,Widowed,Retired,Medicare,Admit,ambulance,May,Sunday,11-14,Admit

In [78]:
cc_df.describe().T["max"].value_counts()

max
1.0    123
2.0     75
4.0      1
3.0      1
Name: count, dtype: int64

In [77]:
cc_df.loc[cc_df["cc_abdominaldistention"] == 2, "cc_abdominaldistention"]

515903    2.0
Name: cc_abdominaldistention, dtype: float64